var myString;
var myNumber;
var myBoolean;
// let strArr : string[];
// let numArr: number[];
var strArr;
var numArr;
var strNumTuple;
myString = 'Hello'.slice(0, 3);
// myString = 'Hello, World';
myNumber = 22;
myBoolean = false;
strArr = ['Hello', 'World'];
numArr = [1, 2, 3, 4, 5];
strNumTuple = ['Hello', 22];
console.log(myString);
console.log(myNumber);
console.log(myBoolean);
console.log(strArr);
console.log(numArr);
console.log(strNumTuple);
